export const TRANSLATIONS = {
    es: {
        langLabel: "Idioma",
        title: "Brújula Emocional",
        subtitle: "Encuentra claridad en lo que sientes.",
        searchPlaceholder: "¿Qué sientes hoy? (ej. Ansiedad, Placer...)",
        recentTitle: "Vistas recientemente",
        closeButton: "Entendido",
        emotionTag: "Emoción",
        feelLabel: "¿Cómo se siente?",
        triggerLabel: "¿Qué la dispara?",
        functionLabel: "¿Para qué sirve?",
        messageLabel: "Lo que te está diciendo:",
        impulseLabel: "Impulso a evitar",
        responseLabel: "Respuesta sugerida",
        emptyTitle: "No encontramos esa emoción",
        emptyHint: "Prueba con otra palabra como \"incertidumbre\", \"calma\" o \"dolor\".",
        openChip: "Ver",
        openEmotionAria: "Abrir emoción",
        openDetailAria: "Abrir detalle de",
        copyButton: "Copiar",
        copiedFeedback: "Copiado",
        shareButton: "Compartir",
        quizTrigger: "¿No sabes lo que sientes?",
        quizTriggerSub: "Descúbrelo en 3 preguntas",
        quizTitle: "¿Qué siento?",
        quizQ1: "¿Cómo sientes tu cuerpo ahora mismo?",
        quizQ1A: "Activado, tenso o acelerado",
        quizQ1B: "Quieto, pesado o tranquilo",
        quizQ2: "¿Cómo describirías lo que sientes?",
        quizQ2A: "Agradable, expansivo o positivo",
        quizQ2B: "Incómodo, difícil o tenso",
        quizQ3: "¿Parece relacionado con algo concreto?",
        quizQ3A: "Sí, algo o alguien lo desencadenó",
        quizQ3B: "No está claro, es más difuso",
        quizResultTitle: "Puede que estés sintiendo...",
        quizBack: "Anterior",
        quizRestart: "Empezar de nuevo",
        quizClose: "Ver todas las emociones",
        settingsLabel: "Configuración",
        themeLabel: "Tema",
        themeLight: "Claro",
        themeAuto: "Auto",
        themeDark: "Oscuro",
        installButton: "Instalar app",
        iosInstallTitle: "Instalar en iPhone/iPad",
        iosInstallStep1: "1. Toca el botón Compartir de Safari (cuadro con flecha hacia arriba).",
        iosInstallStep2: "2. Selecciona \"Añadir a pantalla de inicio\".",
        iosInstallClose: "Entendido",
        checkinTitle: "¿Cómo me siento?",
        moodAgitado: "Agitado",
        moodTriste: "Triste",
        moodConfundido: "Confundido",
        moodBien: "Bien",
        checkinReset: "Ver todas",
        diaryTrigger: "Mi diario emocional",
        diaryTriggerSub: "Solo se guarda en tu dispositivo",
        diaryTitle: "Diario emocional",
        diaryPrivacyNote: "Tus entradas se guardan solo en este dispositivo. Nunca salen de aquí.",
        diaryEmpty: "Aún no hay entradas.",
        diaryAddShort: "Diario",
        diaryNoteLabel: "Nota (opcional)",
        diaryNotePlaceholder: "¿Qué más quieres recordar?",
        diarySaveButton: "Guardar",
        diaryCancelButton: "Cancelar",
        diaryDeleteButton: "Eliminar entrada",
        diaryClearAll: "Borrar todo el diario",
        diaryClearConfirm: "¿Borrar todas las entradas del diario? Esta acción no se puede deshacer.",
        diaryTodayLabel: "Hoy",
        diaryAddedFeedback: "Guardado en tu diario",
        diaryNewEntry: "Nueva entrada",
        diaryPickEmotion: "¿Qué sentiste?",
        navEmociones: "Emociones",
        navCheckin: "¿Qué siento?",
        navDiary: "Diario"
    },
    en: {
        langLabel: "Language",
        title: "Emotional Compass",
        subtitle: "Find clarity in what you feel.",
        searchPlaceholder: "How are you feeling today? (e.g. Anxiety, Joy...)",
        recentTitle: "Recently viewed",
        closeButton: "Got it",
        emotionTag: "Emotion",
        feelLabel: "How does it feel?",
        triggerLabel: "What triggers it?",
        functionLabel: "What is it for?",
        messageLabel: "What this feeling is telling you:",
        impulseLabel: "Impulse to avoid",
        responseLabel: "Suggested response",
        emptyTitle: "We could not find that emotion",
        emptyHint: "Try another word like \"uncertainty\", \"calm\" or \"pain\".",
        openChip: "View",
        openEmotionAria: "Open emotion",
        openDetailAria: "Open details for",
        copyButton: "Copy",
        copiedFeedback: "Copied",
        shareButton: "Share",
        quizTrigger: "Not sure what you feel?",
        quizTriggerSub: "Find out in 3 questions",
        quizTitle: "What am I feeling?",
        quizQ1: "How does your body feel right now?",
        quizQ1A: "Activated, tense or rushing",
        quizQ1B: "Quiet, heavy or calm",
        quizQ2: "How would you describe what you feel?",
        quizQ2A: "Pleasant, expansive or positive",
        quizQ2B: "Uncomfortable, difficult or tense",
        quizQ3: "Does it seem related to something specific?",
        quizQ3A: "Yes, something or someone triggered it",
        quizQ3B: "Not clear, it feels more diffuse",
        quizResultTitle: "You might be feeling...",
        quizBack: "Previous",
        quizRestart: "Start over",
        quizClose: "See all emotions",
        settingsLabel: "Settings",
        themeLabel: "Theme",
        themeLight: "Light",
        themeAuto: "Auto",
        themeDark: "Dark",
        installButton: "Install app",
        iosInstallTitle: "Install on iPhone/iPad",
        iosInstallStep1: "1. Tap Safari's Share button (square with upward arrow).",
        iosInstallStep2: "2. Select \"Add to Home Screen\".",
        iosInstallClose: "Got it",
        checkinTitle: "How do I feel?",
        moodAgitado: "Agitated",
        moodTriste: "Sad",
        moodConfundido: "Confused",
        moodBien: "Good",
        checkinReset: "See all",
        diaryTrigger: "My emotional diary",
        diaryTriggerSub: "Saved only on your device",
        diaryTitle: "Emotional diary",
        diaryPrivacyNote: "Your entries are saved only on this device. They never leave it.",
        diaryEmpty: "No entries yet.",
        diaryAddShort: "Diary",
        diaryNoteLabel: "Note (optional)",
        diaryNotePlaceholder: "What else do you want to remember?",
        diarySaveButton: "Save",
        diaryCancelButton: "Cancel",
        diaryDeleteButton: "Delete entry",
        diaryClearAll: "Clear all diary entries",
        diaryClearConfirm: "Clear all diary entries? This cannot be undone.",
        diaryTodayLabel: "Today",
        diaryAddedFeedback: "Saved to your diary",
        diaryNewEntry: "New entry",
        diaryPickEmotion: "What did you feel?",
        navEmociones: "Emotions",
        navCheckin: "How do I feel?",
        navDiary: "Diary"
    }
};

export const EMOTION_NAME_TRANSLATIONS = {
    Enojo: "Anger",
    Tristeza: "Sadness",
    Miedo: "Fear",
    Ansiedad: "Anxiety",
    Vergüenza: "Shame",
    Culpa: "Guilt",
    Frustración: "Frustration",
    Celos: "Jealousy",
    Soledad: "Loneliness",
    Alegría: "Joy",
    Calma: "Calm",
    Confusión: "Confusion",
    Preocupación: "Worry",
    Felicidad: "Happiness",
    Entusiasmo: "Enthusiasm",
    Placer: "Pleasure",
    Angustia: "Distress",
    Irritabilidad: "Irritability",
    Rechazo: "Rejection",
    Envidia: "Envy",
    Gratitud: "Gratitude",
    Orgullo: "Pride",
    Nostalgia: "Nostalgia",
    Alivio: "Relief",
    Aburrimiento: "Boredom",
    Disgusto: "Disgust",
    "Decepción": "Disappointment",
    Ternura: "Tenderness"
};

export const EMOTION_CONTENT_TRANSLATIONS = {
    Enojo: {
        siente: "Heat, tension, high energy, tight jaw",
        dispara: "Injustice, boundaries crossed, frustration",
        funcion: "Protect boundaries, mobilize change",
        mensaje: "Something is not working for me",
        impulso: "Attack, demand, cut off",
        respuesta: "Pause, name your boundary, ask for a clear change"
    },
    Tristeza: {
        siente: "Heaviness, crying, fatigue, emptiness",
        dispara: "Loss, disappointment, distance",
        funcion: "Process loss, seek support, slow down",
        mensaje: "Something important hurt me",
        impulso: "Isolate, give up",
        respuesta: "Validate your pain, seek support, practice self-care"
    },
    Miedo: {
        siente: "Alertness, acceleration, tension, knot in the stomach",
        dispara: "Risk, threat, uncertainty",
        funcion: "Protect and prepare",
        mensaje: "I perceive danger or vulnerability",
        impulso: "Run away, freeze, avoid",
        respuesta: "Assess real risk, breathe, move forward gradually"
    },
    Ansiedad: {
        siente: "Restlessness, racing mind, urgency",
        dispara: "Uncertainty, anticipation, pressure",
        funcion: "Prepare resources, focus attention",
        mensaje: "This matters and I cannot control it",
        impulso: "Overthink, control, avoid",
        respuesta: "Slow down, prioritize, tolerate uncertainty"
    },
    "Vergüenza": {
        siente: "Facial heat, urge to hide",
        dispara: "Criticism, exposure, social mistakes",
        funcion: "Protect social belonging",
        mensaje: "I fear rejection or judgment",
        impulso: "Hide, justify myself",
        respuesta: "Self-compassion, realistic perspective, repair if needed"
    },
    Culpa: {
        siente: "Inner weight, restlessness, remorse",
        dispara: "Having hurt someone or gone against values",
        funcion: "Repair, adjust behavior",
        mensaje: "Something was not aligned with my values",
        impulso: "Punish yourself, overexplain",
        respuesta: "Repair, apologize, learn"
    },
    "Frustración": {
        siente: "Tension, irritation, impatience",
        dispara: "Obstacles, delay, blockage",
        funcion: "Signal a blocked goal",
        mensaje: "I want something and it is not working",
        impulso: "Force, explode, quit",
        respuesta: "Be flexible, split into steps, ask for help"
    },
    Celos: {
        siente: "Activation, vigilance, insecurity",
        dispara: "Threat of loss, comparison",
        funcion: "Protect the bond, detect needs",
        mensaje: "I fear losing connection or value",
        impulso: "Control, demand, check",
        respuesta: "Express your need, review evidence, strengthen self-esteem"
    },
    Soledad: {
        siente: "Emptiness, nostalgia, low mood",
        dispara: "Disconnection, lack of support",
        funcion: "Motivate connection",
        mensaje: "I need meaningful connection",
        impulso: "Isolate even more",
        respuesta: "Seek gradual and genuine contact"
    },
    "Alegría": {
        siente: "Lightness, energy, expansion",
        dispara: "Achievement, connection, enjoyment",
        funcion: "Reinforce valuable behaviors",
        mensaje: "This nourishes me",
        impulso: "Act impulsively, overindulge",
        respuesta: "Savor it, give thanks, repeat healthy behaviors"
    },
    Calma: {
        siente: "Body softness, steady breathing",
        dispara: "Safety, rest, clarity",
        funcion: "Recovery and balance",
        mensaje: "For now I am safe",
        impulso: "Let your guard down completely",
        respuesta: "Use it to plan and recharge"
    },
    "Confusión": {
        siente: "Mental fog, doubt, blockage",
        dispara: "Contradictory information, ambivalence",
        funcion: "Signal the need for clarity",
        mensaje: "I need more information or time",
        impulso: "Decide impulsively, freeze",
        respuesta: "Ask questions, wait, organize your thoughts"
    },
    "Preocupación": {
        siente: "Busy mind, tension, anticipation, difficulty letting thoughts go",
        dispara: "Uncertainty, responsibility, fear of mistakes or consequences",
        funcion: "Anticipate possible problems and prepare",
        mensaje: "There is something important I want to protect or control",
        impulso: "Overthink, check excessively, seek certainty",
        respuesta: "Prioritize, separate real from imagined, return to the present"
    },
    Felicidad: {
        siente: "Lightness, well-being, relaxation, sense of fullness",
        dispara: "Connection, achievement, safety, pleasant moments",
        funcion: "Reinforce valuable experiences and connection",
        mensaje: "This feels good and I want to keep it",
        impulso: "Cling to it, avoid what disturbs it",
        respuesta: "Allow yourself to enjoy and register the positive"
    },
    Entusiasmo: {
        siente: "High energy, motivation, positive emotion, urge to act",
        dispara: "New projects, interest, excitement, connection",
        funcion: "Mobilize action and exploration",
        mensaje: "There is something that inspires me or matters deeply",
        impulso: "Do too much too fast, commit impulsively",
        respuesta: "Keep motivation with a sustainable pace"
    },
    Placer: {
        siente: "Pleasant sensation, comfort, physical or emotional satisfaction",
        dispara: "Rest, enjoyment, contact, rewarding experiences",
        funcion: "Support well-being and recovery",
        mensaje: "This feels nourishing or satisfying",
        impulso: "Try to repeat it immediately",
        respuesta: "Enjoy consciously and keep balance"
    },
    Angustia: {
        siente: "Pressure, despair, feeling unable to hold something",
        dispara: "Loss of control, intense fear, high uncertainty",
        funcion: "Signal emotional overload or perceived threat",
        mensaje: "Something is overwhelming me",
        impulso: "Escape, isolate, seek immediate relief",
        respuesta: "Regulate your body, ask for support, reduce stimuli"
    },
    Irritabilidad: {
        siente: "Tension, impatience, high sensitivity, easy annoyance",
        dispara: "Fatigue, stress, accumulated frustration, overload",
        funcion: "Signal saturation or need for a pause",
        mensaje: "I am exhausted or something is too much",
        impulso: "Respond sharply, argue, pull away",
        respuesta: "Rest, lower demands, express your need before exploding"
    },
    Rechazo: {
        siente: "Distance, discomfort, dislike or exclusion",
        dispara: "Criticism, disapproval, lack of acceptance or incompatibility",
        funcion: "Protect identity, boundaries, or belonging",
        mensaje: "This does not feel safe or compatible for me",
        impulso: "Pull away, shut down, attack or avoid",
        respuesta: "Explore whether rejection comes from harm or insecurity and respond clearly"
    },
    Envidia: {
        siente: "Bitterness, tension, constant comparison, sense of injustice",
        dispara: "Seeing others' achievements or possessions you desire, social comparison",
        funcion: "Signal what you value but don't have, motivate change",
        mensaje: "There is something I want and feel I don't have access to",
        impulso: "Put others down, sabotage, withdraw",
        respuesta: "Use it as a compass toward your own goals, without comparing yourself"
    },
    Gratitud: {
        siente: "Warmth, openness, lightness, expansion in the chest",
        dispara: "Receiving help, genuine connection, recognizing what you have",
        funcion: "Strengthen bonds, broaden perspective, reinforce well-being",
        mensaje: "Something or someone gave me something valuable",
        impulso: "Take it for granted, not express it",
        respuesta: "Express it, write it down, allow yourself to receive it fully"
    },
    Orgullo: {
        siente: "Expansion, high energy, deep satisfaction, confidence",
        dispara: "Personal achievement, overcoming a challenge, living up to your values",
        funcion: "Reinforce identity and effort-based behaviors",
        mensaje: "I achieved it or I trust who I am",
        impulso: "Brag excessively, become arrogant or dismissive",
        respuesta: "Celebrate with humility, share it genuinely, let it fuel future effort"
    },
    Nostalgia: {
        siente: "Warmth mixed with melancholy, longing, bittersweet sensation",
        dispara: "Memories of the past, places, people, or times that are no longer",
        funcion: "Reinforce identity, value what was lived, connect past and present",
        mensaje: "Something of who I was or lived matters deeply to me",
        impulso: "Live in the past, avoid or escape the present",
        respuesta: "Honor what was lived, bring something from that past consciously into today"
    },
    Alivio: {
        siente: "Release, relaxation, letting go of tension, freer breathing",
        dispara: "End of a threat, resolution of a problem, receiving good news",
        funcion: "Signal that the danger has passed, allow recovery",
        mensaje: "What I feared did not happen or it is over now",
        impulso: "Ignore what caused the stress, skip reflection",
        respuesta: "Rest consciously, use the calm to process and prepare"
    },
    Aburrimiento: {
        siente: "Emptiness, restlessness, lack of motivation, time that does not move",
        dispara: "Lack of stimulation, excessive routine, unclear goals",
        funcion: "Signal need for stimulation, meaning, or a new challenge",
        mensaje: "I need something that activates me or has meaning",
        impulso: "Seek empty distractions, complain, disengage",
        respuesta: "Find a purposeful activity, create something, challenge your mind"
    },
    Disgusto: {
        siente: "Nausea, urge to pull away, body contraction, physical or moral discomfort",
        dispara: "Something perceived as repulsive, unjust, offensive, or incompatible with core values",
        funcion: "Protect from harm (physical or moral), maintain value integrity",
        mensaje: "Something violates my physical or moral limits",
        impulso: "Expel, reject, pull away harshly",
        respuesta: "Name what generates it, set a clear boundary, distance yourself if needed"
    },
    "Decepción": {
        siente: "Quiet heaviness, mild discouragement, emptiness where something was expected",
        dispara: "Unmet expectation, broken promise, outcome below what was hoped for",
        funcion: "Signal that something expected did not arrive, invite readjusting expectations",
        mensaje: "I expected something that did not happen",
        impulso: "Give up, disconnect, look for someone to blame",
        respuesta: "Validate the expectation, assess if it was realistic, redirect your energy"
    },
    Ternura: {
        siente: "Gentle warmth, urge to nurture, chest opening, sensation of wanting to protect",
        dispara: "Something or someone fragile, vulnerable, or cherished — children, pets, intimate moments",
        funcion: "Strengthen bonds, motivate care, deepen connection",
        mensaje: "There is something I want to protect or draw closer",
        impulso: "Hold back the expression, minimize it as silly or unnecessary",
        respuesta: "Allow yourself to express it, draw closer, care without losing your own limits"
    }
};

export const emociones = [
    { nombre: "Enojo", color: "#fecaca", text: "#7f1d1d", siente: "Calor, tensión, energía alta, mandíbula apretada", dispara: "Injusticia, límite invadido, frustración", funcion: "Proteger límites, movilizar cambio", mensaje: "Algo no me está funcionando", impulso: "Atacar, reclamar, cortar", respuesta: "Pausar, nombrar límite, pedir cambio claro" },
    { nombre: "Tristeza", color: "#bfdbfe", text: "#1e3a8a", siente: "Pesadez, llanto, cansancio, vacío", dispara: "Pérdida, decepción, distancia", funcion: "Procesar pérdida, pedir apoyo, bajar ritmo", mensaje: "Algo importante me dolió", impulso: "Aislarse, rendirse", respuesta: "Validar dolor, buscar apoyo, autocuidado" },
    { nombre: "Miedo", color: "#ddd6fe", text: "#4c1d95", siente: "Alerta, aceleración, tensión, nudo estomacal", dispara: "Riesgo, amenaza, incertidumbre", funcion: "Proteger y prepararse", mensaje: "Percibo peligro o vulnerabilidad", impulso: "Huir, congelarse, evitar", respuesta: "Evaluar riesgo real, respirar, avanzar gradual" },
    { nombre: "Ansiedad", color: "#fed7aa", text: "#7c2d12", siente: "Inquietud, mente acelerada, urgencia", dispara: "Incertidumbre, anticipación, presión", funcion: "Preparar recursos, enfocar atención", mensaje: "Algo importa y no lo controlo", impulso: "Sobrepensar, controlar, evitar", respuesta: "Reducir velocidad, priorizar, tolerar incertidumbre" },
    { nombre: "Vergüenza", color: "#fbcfe8", text: "#831843", siente: "Calor facial, ganas de esconderse", dispara: "Crítica, exposición, error social", funcion: "Cuidar pertenencia social", mensaje: "Temo rechazo o juicio", impulso: "Ocultarse, justificarse", respuesta: "Autocompasión, perspectiva realista, reparar si aplica" },
    { nombre: "Culpa", color: "#bbf7d0", text: "#064e3b", siente: "Peso interno, inquietud, remordimiento", dispara: "Haber dañado o ir contra valores", funcion: "Reparar, reajustar conducta", mensaje: "Algo no estuvo alineado con mis valores", impulso: "Castigarse, sobreexplicar", respuesta: "Reparar, disculparse, aprender" },
    { nombre: "Frustración", color: "#fca5a5", text: "#7f1d1d", siente: "Tensión, irritación, impaciencia", dispara: "Obstáculos, demora, bloqueo", funcion: "Señalar meta bloqueada", mensaje: "Quiero algo y no está saliendo", impulso: "Forzar, explotar, abandonar", respuesta: "Flexibilidad, dividir pasos, pedir ayuda" },
    { nombre: "Celos", color: "#d9f99d", text: "#365314", siente: "Activación, vigilancia, inseguridad", dispara: "Amenaza de pérdida, comparación", funcion: "Proteger vínculo, detectar necesidad", mensaje: "Temo perder conexión o valor", impulso: "Controlar, reclamar, revisar", respuesta: "Expresar necesidad, revisar evidencia, fortalecer autoestima" },
    { nombre: "Soledad", color: "#93c5fd", text: "#1e3a8a", siente: "Vacío, nostalgia, desánimo", dispara: "Desconexión, falta de apoyo", funcion: "Motivar conexión", mensaje: "Necesito vínculo significativo", impulso: "Aislarse más", respuesta: "Buscar contacto gradual y genuino" },
    { nombre: "Alegría", color: "#fef08a", text: "#713f12", siente: "Ligereza, energía, expansión", dispara: "Logro, conexión, disfrute", funcion: "Reforzar conductas valiosas", mensaje: "Esto me nutre", impulso: "Actuar impulsivamente, excederse", respuesta: "Saborear, agradecer, repetir conductas sanas" },
    { nombre: "Calma", color: "#a5f3fc", text: "#164e63", siente: "Suavidad corporal, respiración estable", dispara: "Seguridad, descanso, claridad", funcion: "Recuperación y equilibrio", mensaje: "Por ahora estoy a salvo", impulso: "Bajar guardia total", respuesta: "Aprovechar para planear y recargar" },
    { nombre: "Confusión", color: "#ffedd5", text: "#7c2d12", siente: "Niebla mental, duda, bloqueo", dispara: "Información contradictoria, ambivalencia", funcion: "Señalar necesidad de claridad", mensaje: "Me falta información o tiempo", impulso: "Decidir impulsivamente, congelarse", respuesta: "Hacer preguntas, esperar, ordenar ideas" },
    { nombre: "Preocupación", color: "#6b21a8", text: "#ffffff", siente: "Mente ocupada, tensión, anticipación, dificultad para soltar pensamientos", dispara: "Incertidumbre, responsabilidad, miedo a errores o consecuencias", funcion: "Anticipar posibles problemas y prepararse", mensaje: "Hay algo importante que quiero cuidar o controlar", impulso: "Sobrepensar, revisar excesivamente, buscar certeza", respuesta: "Priorizar, distinguir lo real de lo imaginado, regresar al presente" },
    { nombre: "Felicidad", color: "#fde047", text: "#713f12", siente: "Ligereza, bienestar, relajación, sensación de plenitud", dispara: "Conexión, logro, seguridad, momentos agradables", funcion: "Reforzar experiencias valiosas y conexión", mensaje: "Esto me hace bien y quiero conservarlo", impulso: "Aferrarse, evitar lo que la perturba", respuesta: "Permitirse disfrutar y registrar lo positivo" },
    { nombre: "Entusiasmo", color: "#67e8f9", text: "#164e63", siente: "Energía alta, motivación, emoción positiva, impulso de actuar", dispara: "Nuevos proyectos, interés, ilusión, conexión", funcion: "Movilizar acción y exploración", mensaje: "Hay algo que me inspira o importa mucho", impulso: "Hacer demasiado rápido, comprometerse impulsivamente", respuesta: "Mantener motivación con ritmo sostenible" },
    { nombre: "Placer", color: "#f9a8d4", text: "#831843", siente: "Sensación agradable, comodidad, satisfacción corporal o emocional", dispara: "Descanso, disfrute, contacto, experiencias gratificantes", funcion: "Favorecer bienestar y recuperación", mensaje: "Esto se siente nutritivo o satisfactorio", impulso: "Buscar repetir inmediatamente", respuesta: "Disfrutar conscientemente y mantener equilibrio" },
    { nombre: "Angustia", color: "#60a5fa", text: "#1e3a8a", siente: "Opresión, desesperación, sensación de no poder sostener algo", dispara: "Pérdida de control, miedo intenso, incertidumbre alta", funcion: "Señalar saturación emocional o amenaza percibida", mensaje: "Algo me está sobrepasando", impulso: "Escapar, aislarse, buscar alivio inmediato", respuesta: "Regular el cuerpo, pedir apoyo, reducir estímulos" },
    { nombre: "Irritabilidad", color: "#bef264", text: "#365314", siente: "Tensión, impaciencia, sensibilidad alta, facilidad para molestarse", dispara: "Cansancio, estrés, frustración acumulada, sobrecarga", funcion: "Señalar saturación o necesidad de pausa", mensaje: "Estoy agotado o algo me está sobrepasando", impulso: "Responder cortante, discutir, alejarse", respuesta: "Descansar, bajar exigencia, expresar necesidad antes de explotar" },
    { nombre: "Rechazo", color: "#d8b4fe", text: "#4c1d95", siente: "Distancia, incomodidad, desagrado o exclusión", dispara: "Crítica, desaprobación, falta de aceptación o incompatibilidad", funcion: "Proteger identidad, límites o pertenencia", mensaje: "Esto no se siente seguro o compatible para mí", impulso: "Alejarse, cerrarse, atacar o evitar", respuesta: "Explorar si el rechazo viene de daño o inseguridad y responder con claridad" },
    { nombre: "Envidia", color: "#fef9c3", text: "#78350f", siente: "Amargura, tensión, comparación constante, sensación de injusticia", dispara: "Ver logros o bienes ajenos que se desean, comparación social", funcion: "Señalar lo que valoras y no tienes, motivar cambio", mensaje: "Hay algo que deseo y siento que no tengo acceso", impulso: "Denigrar al otro, sabotear, paralizarse", respuesta: "Úsala como brújula hacia tus propias metas, sin compararte" },
    { nombre: "Gratitud", color: "#2dd4bf", text: "#134e4a", siente: "Calidez, apertura, ligereza, expansión en el pecho", dispara: "Recibir ayuda, conexión genuina, reconocer lo que tienes", funcion: "Fortalecer vínculos, ampliar perspectiva, reforzar bienestar", mensaje: "Algo o alguien me aportó algo valioso", impulso: "Dar por sentado, no expresarla", respuesta: "Exprésala, anótala, permítete recibirla plenamente" },
    { nombre: "Orgullo", color: "#a5b4fc", text: "#312e81", siente: "Expansión, energía alta, satisfacción profunda, confianza", dispara: "Logro propio, superar un reto, vivir conforme a tus valores", funcion: "Reforzar identidad y conductas de esfuerzo", mensaje: "Lo logré o confío en quién soy", impulso: "Presumir en exceso, volverse arrogante o despectivo", respuesta: "Celebra con humildad, compártelo genuinamente, deja que impulse el siguiente esfuerzo" },
    { nombre: "Nostalgia", color: "#f0abfc", text: "#701a75", siente: "Calidez mezclada con melancolía, añoranza, sensación agridulce", dispara: "Recuerdos del pasado, lugares, personas o épocas que ya no están", funcion: "Reforzar identidad, valorar lo vivido, conectar pasado y presente", mensaje: "Algo de lo que fui o viví me importa mucho", impulso: "Vivir en el pasado, evitar o escapar el presente", respuesta: "Honra lo vivido, trae algo de ese pasado conscientemente al hoy" },
    { nombre: "Alivio", color: "#6ee7b7", text: "#064e3b", siente: "Descarga, relajación, soltar tensión, respiración más libre", dispara: "Fin de una amenaza, resolución de problema, buenas noticias", funcion: "Señalar que el peligro pasó, permitir recuperación", mensaje: "Lo que temía no ocurrió o ya pasó", impulso: "Ignorar lo que causó el estrés, saltarse la reflexión", respuesta: "Descansa conscientemente, usa la calma para procesar y prepararte" },
    { nombre: "Aburrimiento", color: "#cbd5e1", text: "#334155", siente: "Vacío, inquietud, falta de motivación, tiempo que no avanza", dispara: "Falta de estímulo, rutina excesiva, metas poco claras", funcion: "Señalar necesidad de estimulación, significado o un nuevo desafío", mensaje: "Necesito algo que me active o tenga sentido", impulso: "Buscar distracciones vacías, quejarse, desconectarse", respuesta: "Busca una actividad con propósito, crea algo, desafía tu mente" },
    { nombre: "Disgusto", color: "#d6d3d1", text: "#292524", siente: "Náuseas, ganas de alejarse, contracción corporal, malestar físico o moral", dispara: "Algo percibido como repugnante, injusto, ofensivo o incompatible con valores profundos", funcion: "Proteger de lo dañino (físico o moral), mantener integridad de valores", mensaje: "Algo viola mis límites físicos o morales", impulso: "Expulsar, rechazar, alejarse bruscamente", respuesta: "Nombra lo que lo genera, pon un límite claro, aléjate si es necesario" },
    { nombre: "Decepción", color: "#bae6fd", text: "#0c4a6e", siente: "Pesadez tranquila, desánimo suave, vacío donde esperaba algo", dispara: "Expectativa no cumplida, promesa rota, resultado por debajo de lo esperado", funcion: "Señalar que algo esperado no llegó, invitar a reajustar expectativas", mensaje: "Esperaba algo que no se dio", impulso: "Resignarse, desconectarse, buscar culpables", respuesta: "Valida la expectativa, revisa si era realista, redirige tu energía" },
    { nombre: "Ternura", color: "#ffe4e6", text: "#9f1239", siente: "Calidez suave, ganas de cuidar, apertura en el pecho, sensación de querer proteger", dispara: "Algo o alguien frágil, vulnerable o querido: hijos, mascotas, momentos íntimos", funcion: "Fortalecer vínculos, motivar el cuidado, profundizar la conexión", mensaje: "Hay algo que quiero proteger o acercar", impulso: "Contener la expresión, minimizarla como tontería o debilidad", respuesta: "Permítete expresarla, acércate, cuida sin perder tus propios límites" }
];

export const RECENT_KEY = "brujulaRecientes";
export const LANGUAGE_KEY = "brujulaIdioma";
export const THEME_KEY = "brujulaThema";
export const DIARY_KEY = "brujulaDiario";
export const RECENT_LIMIT = 5;

export const MOOD_CATEGORIES = [
    { key: "agitado",   labelKey: "moodAgitado",   emoji: "😤", color: "#F5A5A0", ink: "#7A2E2E", emotions: ["Enojo", "Frustración", "Irritabilidad", "Ansiedad", "Miedo", "Preocupación", "Angustia", "Envidia", "Disgusto"] },
    { key: "triste",    labelKey: "moodTriste",    emoji: "😢", color: "#A4C3E3", ink: "#1F3F66", emotions: ["Tristeza", "Soledad", "Nostalgia", "Culpa", "Vergüenza", "Rechazo", "Decepción"] },
    { key: "confundido",labelKey: "moodConfundido",emoji: "🤔", color: "#F5D88A", ink: "#7A5A1A", emotions: ["Confusión", "Aburrimiento", "Celos"] },
    { key: "bien",      labelKey: "moodBien",      emoji: "😌", color: "#8FD4AE", ink: "#1E5237", emotions: ["Calma", "Alivio", "Gratitud", "Felicidad", "Alegría", "Orgullo", "Entusiasmo", "Placer", "Ternura"] }
];
